"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Espresso_1 = require("./Espresso");
var DarkRoast_1 = require("./DarkRoast");
var Mocha_1 = require("./Mocha");
var Whip_1 = require("./Whip");
var Soy_1 = require("./Soy");
var HouseBlend_1 = require("./HouseBlend");
var beverage = new Espresso_1.Espresso();
console.log(beverage.getDescription() + " $" + beverage.cost());
var beverage2 = new DarkRoast_1.DarkRoast();
beverage2 = new Mocha_1.Mocha(beverage2);
beverage2 = new Mocha_1.Mocha(beverage2);
beverage2 = new Whip_1.Whip(beverage2);
console.log(beverage2.getDescription() + " $" + beverage2.cost());
var beverage3 = new HouseBlend_1.HouseBlend();
beverage3 = new Soy_1.Soy(beverage3);
beverage3 = new Mocha_1.Mocha(beverage3);
beverage3 = new Whip_1.Whip(beverage3);
console.log(beverage3.getDescription() + " $" + beverage3.cost());
var beverage4 = new Whip_1.Whip(new Mocha_1.Mocha(new Mocha_1.Mocha(new DarkRoast_1.DarkRoast())));
console.log(beverage4.getDescription() + " $" + beverage4.cost());
var beverage5 = new Whip_1.Whip(new Soy_1.Soy(new Mocha_1.Mocha(new HouseBlend_1.HouseBlend())));
console.log(beverage5.getDescription() + " $" + beverage5.cost());
