"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Paladin_1 = require("./Paladin");
var ConsecratedOreBlade_1 = require("./ConsecratedOreBlade");
var FireBall_1 = require("./FireBall");
var Orc_1 = require("./Orc");
var KrushUrRok_1 = require("./KrushUrRok");
var Magician_1 = require("./Magician");
var FireRainl_1 = require("./FireRainl");
var paladin = new Paladin_1.Paladin();
paladin = new ConsecratedOreBlade_1.ConsecratedOreBlade(paladin);
paladin = new FireBall_1.FireBall(paladin);
paladin = new FireBall_1.FireBall(paladin);
console.log(paladin.getDescription() + ": " + paladin.power());
var orc = new Orc_1.Orc();
orc = new KrushUrRok_1.KrushUrRok(orc);
console.log(orc.getDescription() + ": " + orc.power());
var magician = new Magician_1.Magician();
magician = new FireBall_1.FireBall(magician);
magician = new FireBall_1.FireBall(magician);
magician = new FireBall_1.FireBall(magician);
magician = new FireRainl_1.FireRain(magician);
magician = new FireRainl_1.FireRain(magician);
console.log(magician.getDescription() + ": " + magician.power());
